name: macro_calculator
description: A simple app for pace calculation
version: 4.1.0+2

environment:
  sdk: "2.17.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: #i18n
    sdk: flutter
  intl: ^0.17.0        
  cupertino_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  day_night_time_picker: ^1.1.2
  path_provider: ^2.0.11
  provider: ^6.0.3
  screenshot: ^1.2.3
  share_plus: ^4.0.10

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true