name: macro_calculator
description: A simple app for pace calculation
version: 4.1.0+2

environment:
  sdk: "3.5.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: #i18n
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  day_night_time_picker: ^1.3.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  screenshot: ^3.0.0
  share_plus: ^10.1.2
  file_picker: ^5.0.0
  xml: ^6.0.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/translations/
