name: macro_calculator
description: A new Flutter project.
version: 3.3.0+7

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  numberpicker: ^2.1.1
  path_provider: ^2.0.11
  provider: ^6.0.3
  screenshot: ^1.2.3
  share_plus: ^4.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
